### ISSUE TITLE
unable to call MediaFrameSourceGroup.StartASync() in C# 

### ISSUE THREAD

**Issue by argo422** [microsoft/HoloLensForCV#111]
Trying to access Visible Light Cameras in a Unity HL app (C# script in Visual Studio)

async void StartMediaFrameSourceGroup{
... ... ...
... ... ...
 _holoLensMediaFrameSourceGroup = new HoloLensForCV.MediaFrameSourceGroup(... , ... , ...);
... ... ...
... ... ...
await _holoLensMediaFrameSourceGroup.StartASync();
... ... ...
... ... ...
}

Receiving the following issue -->
Exception thrown: 'System.UnauthorizedAccessException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.UnauthorizedAccessException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Streamer.<StartHoloLensMediaFrameSourceGroup>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at UnityEngine.UnitySynchronizationContext.WorkRequest.Invoke() 
(Filename: <Unknown> Line: 0)

**Comment by doughtmw** [comment]
After building your Unity C# project you need to modify the **Package.appxmanifest** file to allow access to research mode media frame source groups. I've made a simple [Unity project](https://github.com/doughtmw/HoloLensForCV-Unity) to integrate the HoloLensForCV repo with Unity using IL2CPP Windows Runtime support that could be helpful!
