### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10061] while running recorder_console.py

### ISSUE THREAD

**Issue by cyrineee** [Microsoft/HoloLensForCV#90]

**Comment by pablospe** [comment]
I think I have a similar problem in linux, I solved with this, perhaps it helps:

[https://github.com/pablospe/HoloLensForCV/commit/4b2bcc7ee9a4375728782d305062b68aa5048f3d](https://github.com/pablospe/HoloLensForCV/commit/4b2bcc7ee9a4375728782d305062b68aa5048f3d)


```
try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen
```

**Comment by cyrineee** [comment]
@pablospe Thanks for the suggestion but when i make these changes 
i get this error :
Traceback (most recent call last):
  File "recorder_console.py", line 678, in <module>
    main()
  File "recorder_console.py", line 602, in main
    args.dev_portal_password)
  File "recorder_console.py", line 79, in connect
    password_manager = urllib.request.HTTPPasswordMgrWithDefaultRealm()
NameError: name 'urllib' is not defined

**Comment by cyrineee** [comment]
i have now these error if u have an idea 
![recorder](https://user-images.githubusercontent.com/42346254/57232283-91dbb100-701c-11e9-9f5a-506e929f86e5.png)
